define(['Backbone', 'LocalStorage', 'Mediator'], function(){
	return {
		storage: {
			buildings		: 'buildings',
			feedEvents		: 'feedEvents',
			eventsQueue		: 'eventQueue',
			jobs			: 'jobs',
			resourceActions	: 'resourceActions',
			resources		: 'resources',
			upgrades		: 'upgrades',
			village			: 'village',
			culture			: 'culture'
		},
		eventVillageData: {
			villagers			: 'villagers',
			newVillagers		: 'newVillagers'
		},
		seasons: ['spring', 'summer', 'autumn', 'winter'],
		events: {
			resourceAction			: 'action:resource',
			builderAction			: 'action:builder',
			upgraderAction			: 'action:upgrader',
			feedWarning				: 'feed:warning',
			feedError				: 'feed:error',
			events					: 'events',
			scheduleEvent			: 'events:schedule',
			triggerEvent			: 'events:trigger',
			checkEventQueue			: 'events:checkqueue',
			lockEvent				: 'events:lock',
			unlockEvent				: 'events:unlock',
			rememberEventData		: 'events:rememberdata',
			enableEvent				: 'events:enable',
			jobs					: 'jobs',
			assignJob				: 'jobs:assign',
			unassignJob				: 'jobs:unassign',
			upgradeJob				: 'jobs:upgrade',
			createJob				: 'jobs:create',
			destroyJob				: 'jobs:destroy',
			collectJobIncome		: 'jobs:income',
			unlockResourceAction	: 'unlock:action:resource',
			unlockResource			: 'unlock:resource',
			unlockUpgrade			: 'unlock:upgrade',
			unlockBuilding			: 'unlock:building',
			unlockCulture			: 'unlock:culture', 
			unlockJob				: 'unlock:job',
			developBuilding			: 'develop:building',
			developUpgrade			: 'develop:upgrade',
			developCulture			: 'develop:culture',
			destroyBuilding			: 'destroy:building',
			destroyUpgrade			: 'destroy:upgrade',
			destroyCulture			: 'destroy:culture',
			gameReset				: 'game:reset',
			resourceInterval		: 'game:interval:resources',
			populationInterval		: 'game:interval:population',
			decreasePopCap			: 'village:destroy:popcap',
			increasePopCap			: 'village:develop:popcap',
			modifyVillage			: 'village:modify',
			gainResource			: 'gain:resource',
			gainVillagers			: 'gain:villagers',
			startPhase				: 'phase:start',
			upgradeResourceAction	: 'upgrade:action:resource'
		},
		variables: {
			developmentMode				: true,
			gainResourceInterval		: 10000,
			gainPopulationInterval		: 300000,
			seasonInterval				: 3000000,
			maxSingleRandomPopGrowth	: 6,
			eventTimeoutMax				: 30000,
			jobPriorities				: 3,
			defaultBuildingCostCurve	: 1.5,
			workerPoolName				: 'forager',
			introductionEventName		: 'intro1',
			initialResourceAction		: 'forage',
			secondResourceAction		: 'chopWood',
			firstBuilding				: 'hut' 
		}
	};
});